# Generated by Django 5.2.12 on 2026-03-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=255, verbose_name='Field 1')),
                ('field2', models.CharField(max_length=255, verbose_name='Field 2')),
                ('field3', models.CharField(max_length=255, verbose_name='Field 3')),
                ('field4', models.CharField(max_length=255, verbose_name='Field 4')),
                ('field5', models.CharField(max_length=255, verbose_name='Field 5')),
            ],
            options={
                'verbose_name': 'Data Record',
                'verbose_name_plural': 'Data Records',
            },
        ),
    ]
