# Generated by Django 5.2.12 on 2026-03-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='Device ID')),
                ('meter_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meter ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('pressure', models.FloatField(default=0, verbose_name='Pressure')),
                ('temperature', models.FloatField(default=0, verbose_name='Temperature')),
                ('volume', models.FloatField(default=0, verbose_name='Volume')),
                ('signal', models.IntegerField(default=0, verbose_name='Signal')),
                ('battery', models.FloatField(default=0, verbose_name='Battery')),
                ('status', models.CharField(default='online', max_length=30, verbose_name='Status')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Data Record',
                'verbose_name_plural': 'Data Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
