# Generated by Django 5.2.12 on 2026-03-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='field1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 1'),
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='field2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 2'),
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='field3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 3'),
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='field4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 4'),
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='field5',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 5'),
        ),
    ]
