# Generated by Django 5.2.11 on 2026-05-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BKGazCurrentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.CharField(max_length=50, verbose_name='Qurilma manzili')),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt')),
                ('work_hours', models.FloatField(blank=True, null=True, verbose_name='Ish soatlari')),
                ('work_volume', models.FloatField(blank=True, null=True, verbose_name='Ishchi hajm (m³)')),
                ('std_volume', models.FloatField(blank=True, null=True, verbose_name='Keltirilgan hajm (m³)')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Bosim')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Harorat')),
                ('correction_coef', models.FloatField(blank=True, null=True, verbose_name='Korreksiya koeffitsienti')),
                ('work_flow', models.FloatField(blank=True, null=True, verbose_name='Ishchi sarf (m³/s)')),
                ('std_flow', models.FloatField(blank=True, null=True, verbose_name='Keltirilgan sarf (m³/s)')),
                ('emergency_bits', models.IntegerField(blank=True, null=True, verbose_name='Xatolik bitlari')),
                ('emergency_active', models.BooleanField(default=False, verbose_name='Xatolik faolmi')),
                ('emergency_codes', models.JSONField(blank=True, default=list, verbose_name='Xatolik kodlari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Joriy Ko'rsatkich",
                'verbose_name_plural': "1. Joriy Ko'rsatkichlar (Current)",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BKGazEmergencyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.CharField(max_length=50, verbose_name='Qurilma manzili')),
                ('timestamp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vaqt')),
                ('code_word', models.IntegerField(blank=True, null=True, verbose_name='Xatolik kodi (raqam)')),
                ('changed', models.BooleanField(default=False, verbose_name="O'zgarganmi")),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Qiymat')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Xatolik turlari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favqulodda Arxiv',
                'verbose_name_plural': '5. Favqulodda Arxivlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BKGazVariableArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.CharField(max_length=50, verbose_name='Qurilma manzili')),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt')),
                ('n2_concentration', models.FloatField(blank=True, null=True, verbose_name='N2 konsentratsiyasi')),
                ('co2_concentration', models.FloatField(blank=True, null=True, verbose_name='CO2 konsentratsiyasi')),
                ('gas_density', models.FloatField(blank=True, null=True, verbose_name='Gaz zichligi')),
                ('baro_pressure', models.FloatField(blank=True, null=True, verbose_name='Barometrik bosim')),
                ('p_lower_bound', models.FloatField(blank=True, null=True, verbose_name='Bosim quyi chegarasi')),
                ('p_upper_bound', models.FloatField(blank=True, null=True, verbose_name='Bosim yuqori chegarasi')),
                ('temperature_sub', models.FloatField(blank=True, null=True, verbose_name='Almashtirish harorati')),
                ('max_flow', models.FloatField(blank=True, null=True, verbose_name='Maks. sarf')),
                ('min_flow', models.FloatField(blank=True, null=True, verbose_name='Min. sarf')),
                ('min_flow_sub', models.FloatField(blank=True, null=True, verbose_name='Min. sarf alm.')),
                ('max_flow_sub', models.FloatField(blank=True, null=True, verbose_name='Maks. sarf alm.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "O'zgaruvchilar Arxivi",
                'verbose_name_plural': "6. O'zgaruvchilar (Settings)",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BKGazDailyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.CharField(max_length=50, verbose_name='Qurilma manzili')),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Bosim')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Harorat')),
                ('work_vol', models.FloatField(blank=True, null=True, verbose_name='Ishchi hajm (sutka)')),
                ('std_vol', models.FloatField(blank=True, null=True, verbose_name='Keltirilgan hajm (sutka)')),
                ('acc_work_vol', models.FloatField(blank=True, null=True, verbose_name="Jami to'plangan ishchi hajm")),
                ('acc_std_vol', models.FloatField(blank=True, null=True, verbose_name="Jami to'plangan keltirilgan hajm")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kunlik Arxiv',
                'verbose_name_plural': '3. Kunlik Arxivlar',
                'ordering': ['-timestamp'],
                'unique_together': {('device_address', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='BKGazHourlyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.CharField(max_length=50, verbose_name='Qurilma manzili')),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt')),
                ('pressure', models.FloatField(blank=True, null=True, verbose_name='Bosim')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Harorat')),
                ('acc_work_vol', models.FloatField(blank=True, null=True, verbose_name="To'plangan ishchi hajm")),
                ('acc_std_vol', models.FloatField(blank=True, null=True, verbose_name="To'plangan keltirilgan hajm")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Soatlik Arxiv',
                'verbose_name_plural': '2. Soatlik Arxivlar',
                'ordering': ['-timestamp'],
                'unique_together': {('device_address', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='BKGazMonthlyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.CharField(max_length=50, verbose_name='Qurilma manzili')),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt')),
                ('work_vol', models.FloatField(blank=True, null=True, verbose_name='Ishchi hajm (oylik)')),
                ('std_vol', models.FloatField(blank=True, null=True, verbose_name='Keltirilgan hajm (oylik)')),
                ('acc_work_vol', models.FloatField(blank=True, null=True, verbose_name="Jami to'plangan ishchi hajm")),
                ('acc_std_vol', models.FloatField(blank=True, null=True, verbose_name="Jami to'plangan keltirilgan hajm")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Oylik Arxiv',
                'verbose_name_plural': '4. Oylik Arxivlar',
                'ordering': ['-timestamp'],
                'unique_together': {('device_address', 'timestamp')},
            },
        ),
    ]
