# Generated by Django 5.2.12 on 2026-06-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bkgazcurrentdata_bkgazemergencyarchive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='archive_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Archive Type'),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='raw_hex',
            field=models.TextField(blank=True, null=True, verbose_name='Raw Hex'),
        ),
        migrations.AlterField(
            model_name='datarecord',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Timestamp'),
        ),
    ]
