# Generated by Django 5.2.12 on 2026-07-21 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_datarecord_archive_type_datarecord_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='Qurilma ID')),
                ('meter_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hisoblagich ID')),
                ('archive_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Arxiv turi')),
                ('start_address', models.CharField(blank=True, max_length=50, null=True, verbose_name="Boshlang'ich manzil")),
                ('end_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yakuniy manzil')),
                ('packet_count', models.IntegerField(verbose_name='Paketlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': "Xom Paket To'plami",
                'verbose_name_plural': "Xom Paket To'plamlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawPacketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(verbose_name='Tartib raqami')),
                ('packet_hex', models.TextField(verbose_name='Xom paket (Hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='base.rawarchivebatch', verbose_name="To'plam")),
            ],
            options={
                'verbose_name': 'Xom Paket',
                'verbose_name_plural': 'Xom Paketlar',
                'ordering': ['batch', 'sequence_number'],
                'unique_together': {('batch', 'sequence_number')},
            },
        ),
    ]
